### ISSUE TITLE
Add support for culture lectures

### ISSUE THREAD

**Issue by cmpute** [lizy14/Tsinghua-UWP#4]
是否考虑增加文素讲座的日历支持？这个对于没有听够讲座的同学其实挺有用的（比如我╮(ツ)╭），不过对学堂公告的分析可能需要比较复杂的正则和过滤逻辑。

**Comment by lizy14** [comment]
很困难。有类似的工作，正则匹配，效果并不好。
https://github.com/lizy14/weixuetang/blob/master/lecture/utils.py
我觉得需要用一些自然语言处理的方法。或者……专人标注？众包？（逃

**Comment by lizy14** [comment]
找到了这个项目：https://github.com/eesast/EasySeminar
fork 一份试了一下，效果还行。 12条解析出10条，其中3条成功取出标题。
我觉得作为公共信息，解析的逻辑可以放在服务端，而且可以加人工干预。

**Comment by cmpute** [comment]
确实放服务端可以让数据维护方便、比较准确，但是弄个服务端比较麻烦吧？还需要维护

**Comment by lizy14** [comment]
现在校历就是放在服务端的。
除了给用户省电、省流量，还要考虑到用户可能没选文素讲座这门课，还可能根本就没登录。

**Comment by cmpute** [comment]
啊这样~ 我还好奇这个校历是从哪搞下来的~
那其实很赞呀，如果是azure的话一个定期的web job应该就可以了（虽然没做过）

**Comment by lizy14** [comment]
v1.2.10 已加入此特性，应用商店审核中。
服务端程序：https://github.com/lizy14/EasySeminar

**Comment by cmpute** [comment]
赞赞赞
