### ISSUE TITLE
Fail to add class info to system calendar

### ISSUE THREAD

**Issue by Billsfriend** [lizy14/Tsinghua-UWP#5]
新学期，根据帮助上的说法，手动刷新了课程表，但是系统日历没有变化，而且显示了感叹号图标。是因为网络学堂2018全面上线的原因？
BTW，GitHub上最新的release是v1.2.15，UMP商店里面的版本号却是1.3.0.0，1.3应该已经包含了最新的针对网络学堂2018的修改了吧？

**Comment by lizy14** [comment]
1.3.0.0已包含针对网络学堂2018的修改。

课程表刷新失败的原因是：最近一周内，网络学堂2018更改了接口。working on fix

**Comment by lizy14** [comment]
v1.3.1 已修复此问题，正等待应用商店审核

**Comment by lizy14** [comment]
released
