### ISSUE TITLE
Refreshing homework failure

### ISSUE THREAD

**Issue by Billsfriend** [lizy14/Tsinghua-UWP#6]
Fail to refresh the status a finished homework. When manually refresh, a "!" appear beside the button.
Additionally. The calendar keeps popping out notification of a deadline even if I clicked "cancel".
即使手动操作，也没有成功刷新已完成的作业状态，只有一个“！”图标。
另外，系统日历总是不停的提醒当天的ddl，即使我点了“取消”（虽然这不无用处

**Comment by lizy14** [comment]
最后6小时内重复提醒的问题已经在最新版本（v1.3.2）中修复。

这一版本同时修复了一个引起作业刷新失败的问题，请到应用商店更新到最新版，以确认你的问题是否仍然存在。

**Comment by Billsfriend** [comment]
问题已解决，感谢！
